@startuml

title __PROJECT's Class Diagram__\n

  namespace assignment4 {
    class assignment4.Board {
    }
  }
  

  namespace assignment4 {
    class assignment4.ComputerPlayerEasy {
    }
  }
  

  namespace assignment4 {
    class assignment4.ComputerPlayerMedium {
    }
  }
  

  namespace assignment4 {
    class assignment4.ConsoleUI {
    }
  }
  

  namespace assignment4 {
    class assignment4.DebugProxy {
    }
  }
  

  namespace assignment4 {
    class assignment4.Game {
    }
  }
  

  namespace assignment4 {
    class assignment4.GameAspect {
    }
  }
  

  namespace assignment4 {
    enum GameModes {
    }
  }
  

  namespace assignment4 {
    class assignment4.Main {
    }
  }
  

  namespace assignment4 {
    enum MenuOptions {
    }
  }
  

  namespace assignment4 {
    interface assignment4.Player {
    }
  }
  

  namespace assignment4 {
    interface assignment4.UserInterface {
    }
  }
  

  namespace assignment4 {
    class assignment4.VirtualPlayerFactory {
    }
  }
  

  namespace tests {
    class tests.BoardTests {
    }
  }
  

  namespace tests {
    class tests.PlayerTest {
    }
  }
  

  namespace tests {
    class tests.UserInerfaceTests {
    }
  }
  

  assignment4.ComputerPlayerEasy .up.|> assignment4.Player
  assignment4.ComputerPlayerMedium .up.|> assignment4.Player
  assignment4.ConsoleUI .up.|> assignment4.UserInterface
  assignment4.DebugProxy .up.|> java.lang.reflect.InvocationHandler
  tests.BoardTests o-- assignment4.UserInterface : userInterface
  tests.PlayerTest o-- assignment4.UserInterface : userInterface


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
